### ISSUE TITLE
Add the search query to the error state

### ISSUE THREAD

**Issue by lisannevvliet** [lisannevvliet/progressive-web-apps-2122#2]
https://github.com/lisannevvliet/progressive-web-apps-2122/blob/3abf7e489155ed8de950526c52d0fd6199d8ba6e/views/index.ejs#L83-L84

**Comment by lisannevvliet** [comment]
I want something like `No products were found with the name/barcode ${query}. Please try again.`. This used to work in JavaScript, but doesn't work in EJS.

**Comment by jornveltrop** [comment]
Misschien kun je een error view maken, zo kun je makkelijk aan de server-side afvangen of er wel of geen producten zijn met een if else statement

**Comment by lisannevvliet** [comment]
Wauw, thanks! Dit werkte :)
