### ISSUE TITLE
html opsplitsen met ejs

### ISSUE THREAD

**Issue by juliandecloe** [lisannevvliet/progressive-web-apps-2122#21]
Je hebt al wel ejs files. Je kan aan de hand van partials (dus head.ejs en foot.etjs) je html opsplitsen. Splits ook elementen op als headers en bepaalde secties of andere elementen die vaker naar voren komen.

Niet per se nodig, maar wel optimaal gebruik van ejs :D

**Comment by lisannevvliet** [comment]
Implemented partials on blocks of code which are used repeatedly.
