### ISSUE TITLE
fonts als een mapje toevoegen

### ISSUE THREAD

**Issue by jody29** [lisannevvliet/progressive-web-apps-2122#22]
Je kunt als je alle fonts in je CORE_FILES wilt zetten je fonts mapje uploaden als een geheel ipv alle fonts een voor een erin

https://github.com/lisannevvliet/progressive-web-apps-2122/blob/058db4fba3e6692c80074417dd66e1dc4a59eb19/static/service-worker.js#L2-L4

**Comment by lisannevvliet** [comment]
Researched this but it isn't as simple as Jody describes it to be. Not going to implement.
